### ISSUE TITLE
wix "toolsPath" to use system path as a default.

### ISSUE THREAD

**Issue by garymazz** [wix-maven/wix-maven-plugin#6]
Currently ${wix.toolsPath} is used to define the path to wix tooling.  The default path for tools is: "${basedir}\target\wix-tools\". 

Please use system path to detect tools before default path.

**Comment by GregDomjan** [comment]
The design was to ensure that the configuration in the pom was honoured and could be run on any system without prior install.
`<toolDirectory/>` is where to unpack the plugin dependency of <toolsPluginArtifactId/> default wix-toollset and  <toolsPluginGroupId/> default or.wixtoolset.maven.

As I don't want to chase down rubbish in my 20 developers environments for different versions of WiX install they are using,  using the system path before the toolDirectory is not something I would support.

However, I'm open to suggestions for alternate methods such as say, a value for 'pre installed' toolkit where it doesn't unpack things.

Feel free to provide a pull request if you find this is urgent, I'll keep this request open to do when I have time otherwise.

Here is a similar example where you can change the toolset version, and I have provided a custom burn bootstrap 

```
            <plugin>
                <groupId>${wixMaven.groupId}</groupId>
                <artifactId>wix-maven-plugin</artifactId>
                <version>${wixMaven.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>${wix.groupId}</groupId>
                        <artifactId>wix-toolset</artifactId>
                        <version>${wix.version}</version>
                    </dependency>
                    <dependency>
                        <artifactId>wix-bootstrap</artifactId>
                        <groupId>my.group</groupId>
                        <version>3</version>
                        <type>nar</type>
                    </dependency>
                </dependencies>
                <configuration>
                    <bootstrapPluginGroupId>my.group</bootstrapPluginGroupId>
                </configuration>
            </plugin>
```
